spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioweb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: logs/spring-boot-logger.log

security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
